# LLM Prompt 配置文件
# 包含所有系统中使用的LLM prompt模板

[prompts.event_summarization]
system_prompt = "请总结以下用户活动记录，包括按照时间顺序记录的键盘输入、鼠标操作和屏幕截图。请用简短的中文描述用户在这段时间内（1）用了什么应用（2）大概做了什么事情，一两句话概括一下。"
test_system_prompt = "你是一个智能助手，请用简洁的中文回答问题。"
test_user_prompt = "你好，请简单介绍一下你自己。"

[prompts.activity_merging.merge_judgment]
system_prompt = "你是一个智能助手，专门判断用户活动是否应该合并。请根据提供的活动描述，判断这两个活动是否属于同一个连续的任务或主题。"
user_prompt_template = """请判断以下两个用户活动是否应该合并为同一个活动：

**当前活动描述：**
{current_summary}

**新活动描述：**
{new_summary}

请考虑以下因素：
1. 活动是否属于同一个任务或主题
2. 活动之间是否有逻辑连续性
3. 活动是否在相同的工作流程中

请以JSON格式返回你的判断结果：
{{
    "should_merge": true/false,
    "confidence": 0.0-1.0,
    "reason": "判断理由",
    "merged_description": "如果合并，请提供合并后的活动描述，一两句话概括一下"
}}

其中：
- should_merge: 是否应该合并（布尔值）
- confidence: 置信度（0.0-1.0之间的浮点数）
- reason: 简短的判断理由
- merged_description: 如果should_merge为true，提供合并后的活动描述；如果为false，可以为空字符串
"""

[prompts.activity_merging.merge_description]
system_prompt = "你是一个智能助手，专门合并用户活动描述。请将多个相关的活动描述合并成一个连贯、简洁的描述，一两句话概括一下。"
user_prompt_template = """请将以下两个活动描述合并成一个连贯的活动描述：

**当前活动描述：**
{current_description}

**新事件描述：**
{new_event_summary}

请生成一个简洁、连贯的合并描述，保持原有的重要信息，并确保描述流畅自然，一两句话概括一下。"""

[prompts.general_summary]
system_prompt = "你是一个智能助手，请用简洁的中文总结用户提供的内容。"



# 配置参数
[config.default_params]
max_tokens = 2000
temperature = 0.7

[config.merge_judgment]
max_tokens = 100
temperature = 0.3

[config.merge_description]
max_tokens = 300
temperature = 0.5

[config.event_summarization]
max_tokens = 2000
temperature = 0.7
